development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] + '_development'%>
  pool: 5
  host: localhost
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_USER_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] + '_test' %>
  pool: 5
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_USER_PASSWORD'] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 